export const CONTACTS_REQ = 'USER.CONTACTS_REQUEST';
export const CONTACTS_SUCCESS = 'USER.CONTACTS_SUCCESS';
export const CONTACTS_FAILURE = 'USER.CONTACTS_FAILURE';

export const NEW_CONTACT_REQ = 'USER.NEW_CONTACT_REQUEST';
export const NEW_CONTACT_SUCCESS = 'USER.NEW_CONTACT_SUCCESS';
export const NEW_CONTACT_FAILURE = 'USER.NEW_CONTACT_FAILURE';
