export const LOGIN_FAILURE = 'AUTH.LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'AUTH.LOGIN_SUCCESS';
export const LOGIN_REQ = 'AUTH.LOGIN_REQUEST';

export const LOGOUT_FAILURE = 'AUTH.LOGOUT_FAILURE';
export const LOGOUT_SUCCESS = 'AUTH.LOGOUT_SUCCESS';
export const LOGOUT_REQ = 'AUTH.LOGOUT_REQ';

export const REGISTER_FAILURE = 'AUTH.REGISTER_FAILURE';
