export const CHANNELS_REQ = 'USER.CHANNELS_REQUEST';
export const CHANNELS_SUCCESS = 'USER.CHANNELS_SUCCESS';
export const CHANNELS_FAILURE = 'USER.CHANNELS_FAILURE';

export const NEW_CHANNEL_REQ = 'USER.NEW_CHANNEL_REQUEST';
export const NEW_CHANNEL_SUCCESS = 'USER.NEW_CHANNEL_SUCCESS';
export const NEW_CHANNEL_FAILURE = 'USER.NEW_CHANNEL_FAILURE';
