export const CHANNELS_REQ = 'USER.CHANNELS_REQUEST';
export const CHANNELS_SUCESS = 'USER.CHANNELS_SUCESS';
export const CHANNELS_FAILURE = 'USER.CHANNELS_FAILURE';

export const CONTACTS_REQ = 'USER.CONTACTS_REQUEST';
export const CONTACTS_SUCESS = 'USER.CONTACTS_SUCESS';
export const CONTACTS_FAILURE = 'USER.CONTACTS_FAILURE';

export const NEW_CHANNEL_REQ = 'USER.NEW_CHANNEL_REQUEST';
export const NEW_CHANNEL_SUCESS = 'USER.NEW_CHANNEL_SUCESS';
export const NEW_CHANNEL_FAILURE = 'USER.NEW_CHANNEL_FAILURE';

export const NEW_CONTACT_REQ = 'USER.NEW_CONTACT_REQUEST';
export const NEW_CONTACT_SUCESS = 'USER.NEW_CONTACT_SUCESS';
export const NEW_CONTACT_FAILURE = 'USER.NEW_CONTACT_FAILURE';
