export const CHANNELS_REQ = 'USER.CHANNELS_REQUEST';
export const CHANNELS_SUCCESS = 'USER.CHANNELS_SUCCESS';
export const CHANNELS_FAILURE = 'USER.CHANNELS_FAILURE';

export const CONTACTS_REQ = 'USER.CONTACTS_REQUEST';
export const CONTACTS_SUCCESS = 'USER.CONTACTS_SUCCESS';
export const CONTACTS_FAILURE = 'USER.CONTACTS_FAILURE';

export const NEW_CHANNEL_REQ = 'USER.NEW_CHANNEL_REQUEST';
export const NEW_CHANNEL_SUCCESS = 'USER.NEW_CHANNEL_SUCCESS';
export const NEW_CHANNEL_FAILURE = 'USER.NEW_CHANNEL_FAILURE';

export const NEW_CONTACT_REQ = 'USER.NEW_CONTACT_REQUEST';
export const NEW_CONTACT_SUCCESS = 'USER.NEW_CONTACT_SUCCESS';
export const NEW_CONTACT_FAILURE = 'USER.NEW_CONTACT_FAILURE';
