export const CHANNELS_REQ = 'CHANNELS.CHANNELS_REQUEST';
export const CHANNELS_SUCCESS = 'CHANNELS.CHANNELS_SUCCESS';
export const CHANNELS_FAILURE = 'CHANNELS.CHANNELS_FAILURE';

export const NEW_CHANNEL_REQ = 'CHANNELS.NEW_CHANNEL_REQUEST';
export const NEW_CHANNEL_SUCCESS = 'CHANNELS.NEW_CHANNEL_SUCCESS';
export const NEW_CHANNEL_FAILURE = 'CHANNELS.NEW_CHANNEL_FAILURE';

export const OPEN_CHANNEL = 'CHANNELS.OPEN_CHANNEL';

export const CHANNEL_USERS_REQ = 'CHANNELS.CHANNEL_USERS_REQUEST';
export const CHANNEL_USERS_SUCCESS = 'CHANNELS.CHANNEL_USERS_SUCCESS';
export const CHANNEL_USERS_FAILURE = 'CHANNELS.CHANNEL_USERS_FAILURE';

export const RENAME_CHANNEL_REQ = 'CHANNELS.RENAME_CHANNEL_REQUEST';
export const RENAME_CHANNEL_SUCCESS = 'CHANNELS.RENAME_CHANNEL_SUCCESS';
export const RENAME_CHANNEL_FAILURE = 'CHANNELS.RENAME_CHANNEL_FAILURE';

export const LEAVE_CHANNEL_REQ = 'CHANNELS.LEAVE_CHANNEL_REQUEST';
export const LEAVE_CHANNEL_SUCCESS = 'CHANNELS.LEAVE_CHANNEL_SUCCESS';
export const LEAVE_CHANNEL_FAILURE = 'CHANNELS.LEAVE_CHANNEL_FAILURE';

export const ADD_TO_CHANNEL_REQ = 'CHANNELS.ADD_TO_CHANNEL_REQUEST';
export const ADD_TO_CHANNEL_SUCCESS = 'CHANNELS.ADD_TO_CHANNEL_SUCCESS';
export const ADD_TO_CHANNEL_FAILURE = 'CHANNELS.ADD_TO_CHANNEL_FAILURE';

export const CHANNEL_TOOLS_OPEN = 'CHANNELS.CHANNEL_TOOLS_OPEN';
export const CHANNEL_TOOLS_CLOSE = 'CHANNELS.CHANNEL_TOOLS_CLOSE';
export const CHANNEL_TOOLS_TOGGLE = 'CHANNELS.CHANNEL_TOOLS_TOGGLE';
